name: gasmatic
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  material_symbols_icons: ^4.2719.3

  # State Management
  flutter_riverpod: ^2.5.1
  # Functional Programming types & patterns
  fpdart: ^1.1.0
  # Date Formatting
  intl: ^0.18.1

  # !: Storage
  # Local Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

  shared_preferences: ^2.2.2

  package_info_plus: ^6.0.0

  # Launch urls for browser and email
  url_launcher: ^6.2.5

  # Environment
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  # Local Database [Tools]
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

  icons_launcher: ^2.1.7

  # Command-line tool for updating Android & iOS splash screen
  flutter_native_splash: ^2.4.0

  # Library for creating mock objects in Dart tests
  mocktail: ^1.0.3

  msix: ^3.16.7

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/env/.env

msix_config:
  include: msix_config.yaml

icons_launcher:
  image_path: "assets/img/app_icon.png"
  platforms:
    android:
      enable: true
      adaptive_background_image: "assets/img/app_icon_bg.png"
      adaptive_foreground_image: "assets/img/app_icon_fg.png"
    ios:
      enable: true
    web:
      enable: false
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

flutter_native_splash:
  color: "#000814"
  image: "assets/img/app_icon_fg.png"
  ios: true
  android: true
  android_12:
    color: "#000814"
